load ("year_utilities.mac");
load ("partition_data.mac");
load ("mutate.mac");
load ("select.mac");
load ("coverage.mac");

/* Analyses:
 *
 * 1. Coverage
 *   1a. Compute coverage year by year for each column, and look for runs of 90% or greater.
 *   1b. Find the intersection of columns which have 90%+ coverage for all stations
 *       (not necessarily in the same years).
 *
 * 2. Temperature
 *   2a. Average max and average min by multi-year periods.
 *       1 year periods, 10 year periods including 2020, 30 year periods including 2010, 100 year periods including 2000.
 *   2b. Exceedance for max and min temperature
 *       min > 70 F, for 1, 10, 30, and 100 year periods, as above, reported as number of days per year.
 *       max > 90 F, for 1, 10, 30, and 100 year periods, as above, reported as number of days per year.
 *   2c. Distribution of temperature difference between max and min.
 *       (max - min) > 20 F, 30 F, or 40 F for 1, 10, 30, and 100 year periods, as above, reported as number of days per year.
 *
 * 3. Precipitation
 *   3a. Total precipitation for for 1, 10, 30, and 100 year periods, as above.
 *   3b. Exceedance for precipitation
 *       precipitation > 0 inch for 1, 10, 30, and 100 year periods, as above, reported as number of days per year.
 *       precipitation > 1 inch for 1, 10, 30, and 100 year periods, as above, reported as number of days per year.
 */

load ("operatingsystem");

if (input: getenv ("INPUT")) = false
    then error ("analyze_weather_data.mac: environment variable INPUT not specified, with no default.");

/* I suppose ATTRIBUTES columns could maybe possibly be present for any data column;
 * the ones listed here are just the ones which are present in the existing CSVs.
 */

df: data_frame_from_file (input, nonnumeric_columns = [ "STATION", "NAME", "DATE", "DAPR_ATTRIBUTES", "MDPR_ATTRIBUTES", "PRCP_ATTRIBUTES", "SNOW_ATTRIBUTES", "SNWD_ATTRIBUTES", "WESD_ATTRIBUTES", "WESF_ATTRIBUTES" ]);

df1: mutate (df by ("DATE_parsed" = lambda([l], map (parse_timedate, l)) of "DATE"));

df1a: mutate (df1 by ("DATE_year" = lambda([l], map (year, l)) of "DATE_parsed"));

df1a_by_STATION: group (df1a by "STATION");

/* this next block of code could be replaced by a map-over-df operation
 * (not the same as aggregate, which works on columns)
 */
coverage_table: make_array (hashed, 1);
for [[station], station_df] in df1a_by_STATION@data
    do (print ("process station", station, "..."),
        coverage_table[station]: coverage_analysis_1 (station_df, 0.9));
coverage_results: nested_data_frame ([ "STATION" ], coverage_table);

/* now print out results for each station */

for [[station], coverage_df] in coverage_results@data
    do block ([coverage1, coverage1_sufficient],
              
              print (matrix_from_data_frame (coverage_df)),

              coverage1: make_data_frame (["variables", "lengthy_runs"], args (%%)),
              print (station = matrix_from_data_frame (coverage1)),

              coverage1_sufficient: select (coverage1 by (lambda ([l], l # []) of "lengthy_runs")),

              print (station = matrix_from_data_frame (coverage1_sufficient)),
              print ("sufficient coverage for", station = coverage1_sufficient@data["variables"]));
