coverage_analysis_1 (df, threshold) :=
    block ([coverage, meets_threshold, meets_threshold_unnested, meets_threshold_runs,
            meets_threshold_places_values_lengths, meets_threshold_runs_long_enough],
           coverage_by_years: aggregate (group (df by "DATE_year") by coverage),
           meets_threshold: aggregate (coverage_by_years by lambda ([x], map (lambda ([y], is (y >= threshold)), x))),
           meets_threshold_unnested: unnest_nested_data_frame (%%),
           meets_threshold_runs: aggregate (%% by find_runs),
           meets_threshold_places_values_lengths: aggregate (%% by reconstruct_places_values_and_lengths),
           meets_threshold_runs_long_enough: aggregate (%% by ensure_value_and_length[true, 10]));

coverage (l) := if l # [] then float (length (sublist (l, lambda ([x], x # false))) / length (l));

/* alternate implementation moved here from mutate.mac
 *
coverage (df) := aggregate (df by coverage1);

coverage1 (l) := if l # [] then lsum (if x # false then 1 else 0, x, l) / length (l);
 *
 */

/* rr is a list of runs structs (at least one), as returned by find_runs.
 * Reconstruct the places at which runs start and return [place, length] pairs,
 * ignoring values.
 */

reconstruct_places_values_and_lengths (rr) := map (reconstruct_places_values_and_lengths_1, rr);

reconstruct_places_values_and_lengths_1 (r) :=
   (accumulate ("+", r@lengths, 1),
    by_threes (rest (%%, -1), r@values, r@lengths));

by_threes (a, b, c) := map (lambda ([a1, b1, c1], [a1, b1, c1]), a, b, c);

ensure_value_and_length [v, n] :=
    buildq ([v, n], lambda ([ll], map (lambda ([l], ensure_value_and_length_1 (v, n, l)), ll)));

ensure_value_and_length_1 (v, n, l) :=
    sublist (l, lambda ([abc], abc[2] = v and abc[3] >= n));

/* Assume that df here is the result of coverage_analysis_1 above. */

sufficient_coverage (df) :=
    (make_data_frame ([ "variables", "lengthy_runs" ], args (matrix_from_data_frame (df))),
     select (%% by (lambda ([l], l # []) of "lengthy_runs")));

/* At this point, df@data["variables"] is the list of variables meeting the coverage criterion,
 * where df is the result of sufficient_coverage.
 */

load ("operatingsystem");

if (input: getenv ("INPUT")) = false
    then error ("analyze_weather_data.mac: environment variable INPUT not specified, with no default.");

/* I suppose ATTRIBUTES columns could maybe possibly be present for any data column;
 * the ones listed here are just the ones which are present in the existing CSVs.
 */

df: data_frame_from_file (input, nonnumeric_columns = [ "STATION", "NAME", "DATE", "DAPR_ATTRIBUTES", "MDPR_ATTRIBUTES", "PRCP_ATTRIBUTES", "SNOW_ATTRIBUTES", "SNWD_ATTRIBUTES", "WESD_ATTRIBUTES", "WESF_ATTRIBUTES" ]);

df1: mutate (df by ("DATE_parsed" = lambda([l], map (parse_timedate, l)) of "DATE"));

df1a: mutate (df1 by ("DATE_year" = lambda([l], map (year, l)) of "DATE_parsed"));

df1a_by_STATION: group (df1a by "STATION");

/* this next block of code could be replaced by a map-over-df operation
 * (not the same as aggregate, which works on columns)
 */
coverage_table: make_array (hashed, 1);
for [[station], station_df] in df1a_by_STATION@data
    do (print ("process station", station, "..."),
        coverage_table[station]: coverage_analysis_1 (station_df, 0.9));
coverage_results: nested_data_frame ([ "STATION" ], coverage_table);

/* now print out results for each station */

for [[station], coverage_df] in coverage_results@data
    do block ([coverage1, coverage1_sufficient],
              
              print (matrix_from_data_frame (coverage_df)),

              coverage1: make_data_frame (["variables", "lengthy_runs"], args (%%)),
              print (station = matrix_from_data_frame (coverage1)),

              coverage1_sufficient: select (coverage1 by (lambda ([l], l # []) of "lengthy_runs")),

              print (station = matrix_from_data_frame (coverage1_sufficient)),
              print ("sufficient coverage for", station = coverage1_sufficient@data["variables"]));

