/* For now, forgo parsing dates since parsed dates aren't any easier to work with,
 * given that dates are big-endian yyyy-mm-dd.
 * I wonder about a scheme in which parsing functions can be specified per column.
 */

data_frame_from_file (input, [columns_specification]) :=
    block ([ data, columns_names, ii, nonnumeric_columns_names, numeric_columns_names,
             nonnumeric_columns_ii, numeric_columns_ii, numeric_columns, nonnumeric_columns,
             maybe_parse, numeric_columns_parsed, all_columns, all_ii,
             column_index_and_column, data_reassembled_by_columns ],

           data: read_matrix (input),

           columns_names: data[1],
           ii: makelist (i, i, 1, length (columns_names)),

           nonnumeric_columns_names:
               if columns_specification # [] and assoc ('nonnumeric_columns, columns_specification) # false
                   /* Silently omit any which are not present in columns_names. */
                   then sublist (assoc ('nonnumeric_columns, columns_specification), lambda ([x], member (x, columns_names)))
                   /* Assume no columns are nonnumeric if not specifically known to be nonnumeric. */
                   else [],
           
           numeric_columns_names:
               if columns_specification # [] and assoc ('numeric_columns, columns_specification) # false
                   /* Silently omit any which are not present in columns_names. */
                   then sublist (assoc ('numeric_columns, columns_specification), lambda ([x], member (x, columns_names)))
                   /* Assume any column is numeric if not specifically known to be nonnumeric. */
                   else sublist (columns_names, lambda ([x], not member (x, nonnumeric_columns_names))),
           
           nonnumeric_columns_ii: sublist_indices (columns_names, lambda ([x], member (x, nonnumeric_columns_names))),
           numeric_columns_ii: sublist_indices (columns_names, lambda ([x], member (x, numeric_columns_names))),
           numeric_columns: submatrix_columns (rest (data), numeric_columns_ii),
           nonnumeric_columns: submatrix_columns (rest (data), nonnumeric_columns_ii),

           maybe_parse: lambda ([x], if stringp (x) then parse_string (x) else x),
           numeric_columns_parsed: map (lambda ([l], map (maybe_parse, l)), numeric_columns),

           /* Reassemble the data matrix comprising numeric and nonnumeric columns in the original order. */

           all_columns: append (nonnumeric_columns, numeric_columns_parsed),
           all_ii: append (nonnumeric_columns_ii, numeric_columns_ii),
           column_index_and_column: makelist ([ all_ii[j], all_columns[j] ], j, 1, length (all_ii)),
           data_reassembled_by_columns: map (second, sort (column_index_and_column)),

           make_data_frame (columns_names, data_reassembled_by_columns));

submatrix_columns (X, ii) :=
    block ([X_transpose: transpose (X)],
           makelist (X_transpose [i], i, ii));

defstruct (data_frame (names, data));

data_frame_p (e) := not atom(e) and op(e) = 'data_frame;

make_data_frame (columns_names, columns_data) :=
    block ([h: make_array (hashed)],
           /* maybe convert lists to 1-d arrays and put that into hash table */
           map (lambda ([name, column], h[name]: column), columns_names, columns_data),
           data_frame (columns_names, h));

prefix ("group");
infix ("by");

matchdeclare (ll, listp);
matchdeclare (dd, lambda ([e], not atom (e) and op (e) = 'data_frame));
matchdeclare ([aa, bb], all);

tellsimpafter (group ll, group1 (ll));

group1 (l) :=
    block ([h: make_array (hashed)],
           for u in unique (l) do h[u]: sublist (l, lambda ([e1], e1 = u)),
           h);

tellsimpafter (group (dd by aa), group_data_frame_by (dd, aa));

group_data_frame_by (df, a) :=
    if not member (a, df@names)
        then error ("group:", a, "is not in the list of names", df@names)
        else block ([h: make_array (hashed),
                     uu: unique (df@data[a]),
                     names_sans_a: delete (a, df@names)],
                    for u in uu
                        do block ([ii: sublist_indices (df@data[a], lambda ([x], x = u)), ll],
                                  ll: makelist (makelist (df@data[x][i], i, ii), x, names_sans_a),
                                  h[u]: make_data_frame (names_sans_a, ll)),
                    h);

infix ("of");

matchdeclare ([aa, bb, ff], all);
defmatch (m1, (aa of bb) by ff);

aggregate (e) :=
    block ([aa, bb, ff],
           if m1 (e) # false
               then if data_frame_p (bb)
                        then if listp (aa)
                                 then map (lambda ([aa1], aggregate (aa1 of bb by ff)), aa)
                                 /* filter out missing values before calling function;
                                  * probably need to allow for other ways to handle them
                                  */
                                 else block ([data1: sublist (bb@data[aa], lambda ([a], a # false))],
                                             ff (data1))
                        else block ([h: make_array (hashed)],
                                    for [k, v] in bb
                                        do arraysetapply (h, k, aggregate (aa of v by ff)),
                                    h));
