/* For now, forgo parsing dates since parsed dates aren't any easier to work with,
 * given that dates are big-endian yyyy-mm-dd.
 * I wonder about a scheme in which parsing functions can be specified per column.
 */

data_frame_from_file (input, [columns_specification]) :=
    block ([ data, columns_names, ii, nonnumeric_columns_names, numeric_columns_names,
             nonnumeric_columns_ii, numeric_columns_ii, numeric_columns, nonnumeric_columns,
             maybe_parse, numeric_columns_parsed, all_columns, all_ii,
             column_index_and_column, data_reassembled_by_columns ],

           data: read_matrix (input),

           columns_names: data[1],
           ii: makelist (i, i, 1, length (columns_names)),

           nonnumeric_columns_names:
               if columns_specification # [] and assoc ('nonnumeric_columns, columns_specification) # false
                   /* Silently omit any which are not present in columns_names. */
                   then sublist (assoc ('nonnumeric_columns, columns_specification), lambda ([x], member (x, columns_names)))
                   /* Assume no columns are nonnumeric if not specifically known to be nonnumeric. */
                   else [],
           
           numeric_columns_names:
               if columns_specification # [] and assoc ('numeric_columns, columns_specification) # false
                   /* Silently omit any which are not present in columns_names. */
                   then sublist (assoc ('numeric_columns, columns_specification), lambda ([x], member (x, columns_names)))
                   /* Assume any column is numeric if not specifically known to be nonnumeric. */
                   else sublist (columns_names, lambda ([x], not member (x, nonnumeric_columns_names))),
           
           nonnumeric_columns_ii: sublist_indices (columns_names, lambda ([x], member (x, nonnumeric_columns_names))),
           numeric_columns_ii: sublist_indices (columns_names, lambda ([x], member (x, numeric_columns_names))),
           numeric_columns: submatrix_columns (rest (data), numeric_columns_ii),
           nonnumeric_columns: submatrix_columns (rest (data), nonnumeric_columns_ii),

           maybe_parse: lambda ([x], if stringp (x) then parse_string (x) else x),
           numeric_columns_parsed: map (lambda ([l], map (maybe_parse, l)), numeric_columns),

           /* Reassemble the data matrix comprising numeric and nonnumeric columns in the original order. */

           all_columns: append (nonnumeric_columns, numeric_columns_parsed),
           all_ii: append (nonnumeric_columns_ii, numeric_columns_ii),
           column_index_and_column: makelist ([ all_ii[j], all_columns[j] ], j, 1, length (all_ii)),
           data_reassembled_by_columns: map (second, sort (column_index_and_column)),

           make_data_frame (columns_names, data_reassembled_by_columns));

submatrix_columns (X, ii) :=
    block ([X_transpose: transpose (X)],
           makelist (X_transpose [i], i, ii));

defstruct (data_frame (names, data));

data_frame_p (e) := not atom(e) and op(e) = 'data_frame;

make_data_frame (columns_names, columns_data) :=
    block ([h: make_array (hashed)],
           /* maybe convert lists to 1-d arrays and put that into hash table */
           map (lambda ([name, column], h[name]: column), columns_names, columns_data),
           data_frame (columns_names, h));

defstruct (nested_data_frame (names, data));

nested_data_frame_p (e) := not atom(e) and op(e) = 'nested_data_frame;

/* consider adjusting binding power so "by" has higher precedence than "group" */
prefix ("group");
infix ("by");

matchdeclare (ll, listp);
matchdeclare (dd, lambda ([e], not atom (e) and op (e) = 'data_frame));
matchdeclare (aa, atom);

tellsimpafter (group (dd by aa), group_data_frame_by (dd, [ aa ]));
tellsimpafter (group (dd by ll), group_data_frame_by (dd, ll));

group_data_frame_by (df, aa) :=
    if not every (lambda ([x], member (x, df@names)), aa)
        then error ("group: not every element of", aa, "is in the list of names", df@names)
        else block ([h, uu, names_sans_aa, aa_values],
                    /* work around incoherent behavior of make_array:
                     * need to supply number of 1's equal to the number of keys
                     * e.g. make_array(hashed, 1, 1) for two keys.
                     */
                    h: apply (make_array, cons (hashed, makelist (1, length (aa)))),
                    uu: unique (reshape (makelist (df@data[a], a, aa), [any, length (aa)], by_columns)),
                    names_sans_aa: df@names,
                    for a in aa do names_sans_aa: delete (a, names_sans_aa),
                    aa_values: reshape (makelist (df@data[a], a, aa), [any, length (aa)], by_columns),
                    for u in uu
                        do block ([ii: sublist_indices (aa_values, lambda ([x], x = u)), ll],
                                  ll: makelist (makelist (df@data[x][i], i, ii), x, names_sans_aa),
                                  arraysetapply (h, u, make_data_frame (names_sans_aa, ll))),
                    nested_data_frame (aa, h));

push ("../**/*.mac", file_search_maxima);
push ("../**/*.lisp", file_search_lisp);

load ("reshape");

infix ("of");

matchdeclare ([aa, bb, ff], all);
defmatch (m1, (aa of bb) by ff);
defmatch (m2, bb by ff);

aggregate (e) :=
    block ([aa, bb, ff],
           if m1 (e) # false
               then aggregate1 (aa, bb, ff)
           elseif m2 (e) # false
               then aggregate1 (false, bb, ff));

aggregate1 (aa, bb, ff) :=
    if data_frame_p (bb)
        then block ([h: apply (make_array, cons (hashed, makelist (1, length (bb@names)))), fdata],
                    /* filter out missing values before calling function;
                     * probably need to allow for other ways to handle them
                     *
                     * Also, bit of "do what I mean" going on here:
                     * if aa isn't already a list, make it a list of one element.
                     * Likewise, if result of ff isn't a list, make it a list of one element.
                     */
                    aa: if aa = false then bb@names else (if listp (aa) then aa else [aa]),
                    fdata: makelist (ff (sublist (bb@data[aa1], lambda ([a], a # false))), aa1, aa),
                    for i thru length (aa) do h[aa[i]]: if listp (fdata[i]) then fdata[i] else [ fdata[i] ],
                    data_frame (aa, h))
    elseif nested_data_frame_p (bb)
        then block ([h: apply (make_array, cons (hashed, makelist (1, length (bb@names))))],
                    for [k, v] in bb@data
                        do arraysetapply (h, k, aggregate1 (aa, v, ff)),
                    nested_data_frame (bb@names, h));

matchdeclare ([names, data], all);

defrule (equation_list_from_data_frame_1, data_frame (names, data), makelist (x = data[x], x, names));

defrule (equation_list_from_nested_data_frame_1,
         nested_data_frame (names, data),
         block ([e: []],
                for [k, v] in data do push (map (lambda ([a, b], a = b), names, k) = v, e),
                /* sort the result -- the only effect is to put the key combinations in ascending order */
                sort (e)));
         
equation_list_from_data_frame (df) :=
    apply1 (df, equation_list_from_nested_data_frame_1, equation_list_from_data_frame_1);

defrule (matrix_from_data_frame_1, data_frame (names, data), cons (names, transpose (apply (matrix, makelist (data[x], x, names)))));

matrix_from_data_frame (df) :=
    apply1 (df, equation_list_from_nested_data_frame_1, matrix_from_data_frame_1);
