load ("year_utilities.mac");
load ("partition_data.mac");
load ("mutate.mac");
load ("select.mac");

/* Analyses:
 *
 * 1. Coverage
 *   1a. Compute coverage year by year for each column, and look for runs of 90% or greater.
 *   1b. Find the intersection of columns which have 90%+ coverage for all stations
 *       (not necessarily in the same years).
 *
 * 2. Temperature
 *   2a. Average max and average min by multi-year periods.
 *       1 year periods, 10 year periods including 2020, 30 year periods including 2010, 100 year periods including 2000.
 *   2b. Exceedance for max and min temperature
 *       min > 70 F, for 1, 10, 30, and 100 year periods, as above, reported as number of days per year.
 *       max > 90 F, for 1, 10, 30, and 100 year periods, as above, reported as number of days per year.
 *   2c. Distribution of temperature difference between max and min.
 *       (max - min) > 20 F, 30 F, or 40 F for 1, 10, 30, and 100 year periods, as above, reported as number of days per year.
 *
 * 3. Precipitation
 *   3a. Total precipitation for for 1, 10, 30, and 100 year periods, as above.
 *   3b. Exceedance for precipitation
 *       precipitation > 0 inch for 1, 10, 30, and 100 year periods, as above, reported as number of days per year.
 *       precipitation > 1 inch for 1, 10, 30, and 100 year periods, as above, reported as number of days per year.
 *   3c. Total precipitation by months or seasons for 1, 10, 30, and 100 year periods.
 */

load ("operatingsystem");

if (input: getenv ("INPUT")) = false
    then error ("analyze_weather_data.mac: environment variable INPUT not specified, with no default.");

/* I suppose ATTRIBUTES columns could maybe possibly be present for any data column;
 * the ones listed here are just the ones which are present in the existing CSVs.
 */

df: data_frame_from_file (input, nonnumeric_columns = [ "STATION", "NAME", "DATE", "DAPR_ATTRIBUTES", "MDPR_ATTRIBUTES", "PRCP_ATTRIBUTES", "SNOW_ATTRIBUTES", "SNWD_ATTRIBUTES", "WESD_ATTRIBUTES", "WESF_ATTRIBUTES" ]);

df1: mutate (df by ("DATE_parsed" = lambda([l], map (parse_timedate, l)) of "DATE"));

df1a: mutate (df1 by ("DATE_year" = lambda([l], map (year, l)) of "DATE_parsed"));

floor10 (x) := 10 * floor (x / 10);
floor100 (x) := 100 * floor (x / 100);

df1b: mutate (df1a by [ "DATE_decade" = lambda ([l], map (floor10, l)) of "DATE_year", "DATE_century" = lambda ([l], map (floor100, l)) of "DATE_year" ]);

df1b_by_STATION: group (df1b by "STATION");

/* For analysis of 1 year to multiple years, filter out years for which daily data coverage is less than 90%.
 * Implement that by grouping by years, filtering out years with insufficient coverage,
 * then ungrouping and regrouping for the specified number of years.
 * The last ungrouping/regrouping step is a no-op when the analysis period is one year
 * and can therefore be omitted.
 */

precipitation_analysis (df, grouping_field, n_years) :=
    if n_years = 1 and grouping_field = "DATE_year"
        then precipitation_analysis_1 (df)
    elseif n_years > 1 and grouping_field # "DATE_year"
        then precipitation_analysis_2 (df, grouping_field, n_years)
        else error ("precipitation_analysis: not sure how to handle n_years =", n_years, "and grouping_field =", grouping_field);

precipitation_analysis_1 (df) :=
    block ([df1, df2, df3, h: make_array (hashed, 1), c],
          df1: group (select (["DATE_year", "PRCP"] from df) by "DATE_year"),
          for [[y], a] in df1@data
              do if (c: simple_annual_coverage (a@data["PRCP"])) >= 0.9 then h[y]: a
                     else print ("precipitation_analysis_1: omit year", y, "(simple annual coverage =", c, ")"),
          df2: nested_data_frame (df1@names, h),
          df3: aggregate (df2 by annualized_mean),
          unnest_nested_data_frame (df3),
          matrix_from_data_frame (%%));

precipitation_analysis_2 (df, grouping_field, n_years) :=
    block ([df1, df2, df3, df4, df5, h: make_array (hashed, 1), c],
          df1: group (select ([grouping_field, "DATE_year", "PRCP"] from df) by "DATE_year"),
          for [[y], a] in df1@data
              do if (c: simple_annual_coverage (a@data["PRCP"])) >= 0.9 then h[y]: a
                     else print ("precipitation_analysis_2: omit year", y, "(simple annual coverage =", c, ")"),
          df2: nested_data_frame (df1@names, h),
          df3: unnest_nested_data_frame (df2),
          df4: group (select ([grouping_field, "PRCP"] from df3) by grouping_field),
          df5: aggregate (df4 by annualized_mean),
          unnest_nested_data_frame (df5),
          matrix_from_data_frame (%%));

annualized_mean (l) := 365.2425 * clean_mean (l);

/* Assume there is exactly one value, be it missing or not, per day.
 * Assess coverage as the proportion of nonmissing values per nominal year.
 */

simple_annual_coverage (l) :=
    block ([n_not_missing: lsum (if x # false then 1 else 0, x, l)],
           n_not_missing / 365.2425);

clean_mean (l) := block ([n], l: sublist (l, lambda ([x], x # false)), n: length (l), if n > 0 then lsum (x, x, l) / n);

map_over_df (f, df) :=
    block ([h: make_array (hashed, 1)],
            for [[k], df1] in df@data
                do (print ("map_over_df: process key", k, "..."),
                    h[k]: f (df1)),
            nested_data_frame (df@names, h));

foo (df) := matrix_from_data_frame (unnest_nested_data_frame (df));

fpprintprec: 6;

precipitation_df_1: map_over_df (foo, map_over_df (lambda ([df], precipitation_analysis (df, "DATE_year", 1)), df1b_by_STATION));
precipitation_df_10: map_over_df (foo, map_over_df (lambda ([df], precipitation_analysis (df, "DATE_decade", 10)), df1b_by_STATION));
precipitation_df_100: map_over_df (foo, map_over_df (lambda ([df], precipitation_analysis (df, "DATE_century", 100)), df1b_by_STATION));

/* now print out results for each station */

map_over_df (print, precipitation_df_1);
map_over_df (print, precipitation_df_10);
map_over_df (print, precipitation_df_100);
