(if ?mget (group_data_frame_by, ?mexpr) = false then load ("partition_data.mac"),
 0);
0;

(aa: [1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0],
 bb: [0, 0, 1, 0, 0, 1, 2, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 2, 1, 1, 1, 2, 2, 2, 1, 0, 2, 0, 2, 1, 0, 0, 2, 0, 1, 0, 1, 1, 1, 0, 2, 1, 1, 0, 0, 0, 0, 2, 2, 1],
 cc: [13, 13, 3, 6, 16, 16, 10, 10, 7, 15, 3, 15, 5, 19, 19, 12, 10, 10, 18, 0, 12, 11, 19, 17, 9, 9, 3, 4, 12, 1, 9, 6, 8, 9, 18, 18, 16, 7, 9, 19, 11, 17, 12, 15, 0, 19, 8, 14, 16, 15],
 dd: [55, 49, 12, 81, 92, 0, 26, 16, 13, 82, 75, 40, 29, 71, 9, 24, 54, 20, 76, 64, 96, 45, 62, 32, 57, 8, 38, 63, 85, 74, 88, 44, 19, 74, 98, 90, 48, 89, 26, 10, 10, 38, 79, 71, 40, 94, 51, 49, 33, 86],
 df1: make_data_frame (["aa", "bb", "cc", "dd"], [aa, bb, cc, dd]),
 equation_list_from_data_frame (df1));
''([ "aa" = aa, "bb" = bb, "cc" = cc, "dd" = dd ]);

(df1_by_aa: group (df1 by "aa"),
 equation_list_from_data_frame (df1_by_aa));
[["aa" = 0] = ["bb" = [1,0,0,1,0,0,1,1,1,1,2,2,0,2,0,1,0,0,1,1,0,0,1],
               "cc" = [3,6,15,3,5,12,10,18,0,12,19,17,9,3,4,1,9,6,7,9,19,8,15],
               "dd" = [12,81,82,75,29,24,54,76,64,96,62,32,8,38,63,74,88,44,89,26,10,51,86]],
 ["aa" = 1] = ["bb" = [0,0,0,1,2,2,0,1,2,0,2,2,1,2,2,0,1,0,1,2,1,1,0,0,0,2,2],
               "cc" = [13,13,16,16,10,10,7,15,19,19,10,11,9,12,8,9,18,18,16,11,17,12,15,0,19,14,16],
               "dd" = [55,49,92,0,26,16,13,40,71,9,20,45,57,85,19,74,98,90,48,10,38,79,71,40,94,49,33]]];


(df1_by_aa_bb: group (df1 by ["aa", "bb"]),
 equation_list_from_data_frame (df1_by_aa_bb));
[["aa" = 0,"bb" = 0] = ["cc" = [6,15,5,12,9,4,9,6,19,8],
                        "dd" = [81,82,29,24,8,63,88,44,10,51]],
 ["aa" = 0,"bb" = 1] = ["cc" = [3,3,10,18,0,12,1,7,9,15],
                        "dd" = [12,75,54,76,64,96,74,89,26,86]],
 ["aa" = 0,"bb" = 2] = ["cc" = [19,17,3],
                        "dd" = [62,32,38]],
 ["aa" = 1,"bb" = 0] = ["cc" = [13,13,16,7,19,9,18,15,0,19],
                        "dd" = [55,49,92,13,9,74,90,71,40,94]],
 ["aa" = 1,"bb" = 1] = ["cc" = [16,15,9,18,16,17,12],
                        "dd" = [0,40,57,98,48,38,79]],
 ["aa" = 1,"bb" = 2] = ["cc" = [10,10,19,10,11,12,8,11,14,16],
                        "dd" = [26,16,71,20,45,85,19,10,49,33]]];

(mymean (x) := if length (x) > 0 then lsum (x1, x1, x) / length (x), 0);
0;

(df1_mean: aggregate (df1 by mymean),
 matrix_from_data_frame (df1_mean));
''(matrix (["aa", "bb", "cc", "dd"], [mymean (aa), mymean (bb), mymean (cc), mymean (dd)]));

(df1_by_aa_mean: aggregate (df1_by_aa by mymean),
 equation_list_from_data_frame (df1_by_aa_mean));
''([["aa" = 0] = ["bb" = [ mymean ([1,0,0,1,0,0,1,1,1,1,2,2,0,2,0,1,0,0,1,1,0,0,1]) ],
                  "cc" = [ mymean ([3,6,15,3,5,12,10,18,0,12,19,17,9,3,4,1,9,6,7,9,19,8,15]) ],
                  "dd" = [ mymean ([12,81,82,75,29,24,54,76,64,96,62,32,8,38,63,74,88,44,89,26,10,51,86]) ]],
    ["aa" = 1] = ["bb" = [ mymean ([0,0,0,1,2,2,0,1,2,0,2,2,1,2,2,0,1,0,1,2,1,1,0,0,0,2,2]) ],
                  "cc" = [ mymean ([13,13,16,16,10,10,7,15,19,19,10,11,9,12,8,9,18,18,16,11,17,12,15,0,19,14,16]) ],
                  "dd" = [ mymean ([55,49,92,0,26,16,13,40,71,9,20,45,57,85,19,74,98,90,48,10,38,79,71,40,94,49,33]) ]]]);

(df1_by_aa_bb_mean: aggregate (df1_by_aa_bb by mymean),
 equation_list_from_data_frame (df1_by_aa_bb_mean));
''([["aa" = 0,"bb" = 0] = ["cc" = [ mymean ([6,15,5,12,9,4,9,6,19,8]) ],
                           "dd" = [ mymean ([81,82,29,24,8,63,88,44,10,51]) ]],
    ["aa" = 0,"bb" = 1] = ["cc" = [ mymean ([3,3,10,18,0,12,1,7,9,15]) ],
                           "dd" = [ mymean ([12,75,54,76,64,96,74,89,26,86]) ]],
    ["aa" = 0,"bb" = 2] = ["cc" = [ mymean ([19,17,3]) ],
                           "dd" = [ mymean ([62,32,38]) ]],
    ["aa" = 1,"bb" = 0] = ["cc" = [ mymean ([13,13,16,7,19,9,18,15,0,19]) ],
                           "dd" = [ mymean ([55,49,92,13,9,74,90,71,40,94]) ]],
    ["aa" = 1,"bb" = 1] = ["cc" = [ mymean ([16,15,9,18,16,17,12]) ],
                           "dd" = [ mymean ([0,40,57,98,48,38,79]) ]],
    ["aa" = 1,"bb" = 2] = ["cc" = [ mymean ([10,10,19,10,11,12,8,11,14,16]) ],
                           "dd" = [ mymean ([26,16,71,20,45,85,19,10,49,33]) ]]]);

/* not sure if the stuff about selecting columns in aggregate is going to be replaced by a separate 'mutate' step or what;
 * anyway here are some tests for the existing functionality.
 */

(cc_of_df1_mean: aggregate (("cc" of df1) by mymean),
 matrix_from_data_frame (cc_of_df1_mean));
''(matrix (["cc"], [ mymean (cc) ]));

(bb_dd_of_df1_mean: aggregate (([ "bb", "dd" ] of df1) by mymean),
 matrix_from_data_frame (bb_dd_of_df1_mean));
''(matrix (["bb", "dd"], [mymean (bb), mymean (dd)]));

(dd_of_df1_by_aa_mean: aggregate (("dd" of df1_by_aa) by mymean),
 equation_list_from_data_frame (dd_of_df1_by_aa_mean));
''([["aa" = 0] = [ "dd" = [ mymean ([12,81,82,75,29,24,54,76,64,96,62,32,8,38,63,74,88,44,89,26,10,51,86]) ]],
    ["aa" = 1] = [ "dd" = [ mymean ([55,49,92,0,26,16,13,40,71,9,20,45,57,85,19,74,98,90,48,10,38,79,71,40,94,49,33]) ]]]);

(dd_of_df1_by_aa_bb_mean: aggregate (("cc" of df1_by_aa_bb) by mymean),
 equation_list_from_data_frame (dd_of_df1_by_aa_bb_mean));
''([["aa" = 0,"bb" = 0] = ["cc" = [ mymean ([6,15,5,12,9,4,9,6,19,8]) ]],
    ["aa" = 0,"bb" = 1] = ["cc" = [ mymean ([3,3,10,18,0,12,1,7,9,15]) ]],
    ["aa" = 0,"bb" = 2] = ["cc" = [ mymean ([19,17,3]) ]],
    ["aa" = 1,"bb" = 0] = ["cc" = [ mymean ([13,13,16,7,19,9,18,15,0,19]) ]],
    ["aa" = 1,"bb" = 1] = ["cc" = [ mymean ([16,15,9,18,16,17,12]) ]],
    ["aa" = 1,"bb" = 2] = ["cc" = [ mymean ([10,10,19,10,11,12,8,11,14,16]) ]]]);

df1_matrix: matrix_from_data_frame (df1);
''(transpose (matrix (cons ("aa", aa), cons ("bb", bb), cons ("cc", cc), cons ("dd", dd))));

unnest_nested_data_frame (df1_by_aa);
''(apply (matrix, cons (first (df1_matrix), sort (rest (args (df1_matrix)), lambda ([a, b], a[1] < b[1])))));

unnest_nested_data_frame (df1_by_aa_bb);
''(apply (matrix, cons (first (df1_matrix), sort (rest (args (df1_matrix)), lambda ([a, b], orderlessp (firstn (a, 2), firstn (b, 2)))))));

unnest_nested_data_frame (df1_by_aa_mean);
''(matrix (["aa", "bb", "cc", "dd"],
           [ 0, mymean ([1,0,0,1,0,0,1,1,1,1,2,2,0,2,0,1,0,0,1,1,0,0,1]),
                mymean ([3,6,15,3,5,12,10,18,0,12,19,17,9,3,4,1,9,6,7,9,19,8,15]),
                mymean ([12,81,82,75,29,24,54,76,64,96,62,32,8,38,63,74,88,44,89,26,10,51,86]) ],
           [ 1, mymean ([0,0,0,1,2,2,0,1,2,0,2,2,1,2,2,0,1,0,1,2,1,1,0,0,0,2,2]),
                mymean ([13,13,16,16,10,10,7,15,19,19,10,11,9,12,8,9,18,18,16,11,17,12,15,0,19,14,16]),
                mymean ([55,49,92,0,26,16,13,40,71,9,20,45,57,85,19,74,98,90,48,10,38,79,71,40,94,49,33]) ]));

unnest_nested_data_frame (df1_by_aa_bb_mean);
''(matrix (["aa", "bb", "cc", "dd"],
           [ 0, 0, mymean ([6,15,5,12,9,4,9,6,19,8]), mymean ([81,82,29,24,8,63,88,44,10,51]) ],
           [ 0, 1, mymean ([3,3,10,18,0,12,1,7,9,15]), mymean ([12,75,54,76,64,96,74,89,26,86]) ],
           [ 0, 2, mymean ([19,17,3]), mymean ([62,32,38]) ],
           [ 1, 0, mymean ([13,13,16,7,19,9,18,15,0,19]), mymean ([55,49,92,13,9,74,90,71,40,94]) ],
           [ 1, 1, mymean ([16,15,9,18,16,17,12]), mymean ([0,40,57,98,48,38,79]) ],
           [ 1, 2, mymean ([10,10,19,10,11,12,8,11,14,16]), mymean ([26,16,71,20,45,85,19,10,49,33]) ]));
