load ("year_utilities.mac");
load ("partition_data.mac");
load ("mutate.mac");
load ("select.mac");

/* Analyses:
 *
 * 1. Coverage
 *   1a. Compute coverage year by year for each column, and look for runs of 90% or greater.
 *   1b. Find the intersection of columns which have 90%+ coverage for all stations
 *       (not necessarily in the same years).
 *
 * 2. Temperature
 *   2a. Average max and average min by multi-year periods.
 *       1 year periods, 10 year periods including 2020, 30 year periods including 2010, 100 year periods including 2000.
 *   2b. Exceedance for max and min temperature
 *       min > 70 F, for 1, 10, 30, and 100 year periods, as above, reported as number of days per year.
 *       max > 90 F, for 1, 10, 30, and 100 year periods, as above, reported as number of days per year.
 *   2c. Distribution of temperature difference between max and min.
 *       (max - min) > 20 F, 30 F, or 40 F for 1, 10, 30, and 100 year periods, as above, reported as number of days per year.
 *
 * 3. Precipitation
 *   3a. Total precipitation for for 1, 10, 30, and 100 year periods, as above.
 *   3b. Exceedance for precipitation
 *       precipitation > 0 inch for 1, 10, 30, and 100 year periods, as above, reported as number of days per year.
 *       precipitation > 1 inch for 1, 10, 30, and 100 year periods, as above, reported as number of days per year.
 *   3c. Total precipitation by months or seasons for 1, 10, 30, and 100 year periods.
 */

load ("operatingsystem");

if (input: getenv ("INPUT")) = false
    then error ("temperature_analysis.mac: environment variable INPUT not specified, with no default.");

/* I suppose ATTRIBUTES columns could maybe possibly be present for any data column;
 * the ones listed here are just the ones which are present in the existing CSVs.
 */

df: data_frame_from_file (input, nonnumeric_columns = [ "STATION", "NAME", "DATE", "DAPR_ATTRIBUTES", "MDPR_ATTRIBUTES", "PRCP_ATTRIBUTES", "SNOW_ATTRIBUTES", "SNWD_ATTRIBUTES", "WESD_ATTRIBUTES", "WESF_ATTRIBUTES" ]);

df1: mutate (df by ("DATE_parsed" = lambda([l], map (parse_timedate, l)) of "DATE"));

df1a: mutate (df1 by ("DATE_year" = lambda([l], map (year, l)) of "DATE_parsed"));

floor10 (x) := 10 * floor (x / 10);
floor30 (x) := 1980 + 30 * floor ((x - 1980) / 30);
floor100 (x) := 100 * floor (x / 100);

defstruct (month_day (month, day));

L: [
    "DATE_month_day" = lambda ([l], map (month_day, map (month, l), map (day_of_month, l))) of "DATE_parsed",
    "DATE_month" = lambda ([l], map (month, l)) of "DATE_parsed",
    "DATE_decade" = lambda ([l], map (floor10, l)) of "DATE_year",
    "DATE_30year" = lambda ([l], map (floor30, l)) of "DATE_year",
    "DATE_century" = lambda ([l], map (floor100, l)) of "DATE_year"
];

df1b: mutate (df1a by L);

df1b_by_STATION: group (df1b by "STATION");

/* For analysis of 1 year to multiple years, filter out years for which daily data coverage is less than 90%.
 * Implement that by grouping by years, filtering out years with insufficient coverage,
 * then ungrouping and regrouping for the specified number of years.
 * The last ungrouping/regrouping step is a no-op when the analysis period is one year
 * and can therefore be omitted.
 */

temperature_analysis (df, grouping_field, f) :=
    if grouping_field = "DATE_year"
        then temperature_analysis_1 (df, f)
        else temperature_analysis_2 (df, grouping_field, f);

temperature_analysis_1 (df, f) :=
    block ([df1, df2, df3, h: make_array (hashed, 1), c],
          df1: group (select (["DATE_year", "TMIN", "TMAX"] from df) by "DATE_year"),
          for [[y], a] in df1@data
              /* coverage of TMAX is almost certainly the same as for TMIN,
               * but compute both and look at the smaller one, on general principle.
               */
              do if (c: min (simple_annual_coverage (a@data["TMIN"]), simple_annual_coverage (a@data["TMAX"]))) >= 0.9 then h[y]: a
                     else print ("temperature_analysis_1: omit year", y, "(simple annual coverage =", c, ")"),
          df2: nested_data_frame (df1@names, h),
          df3: aggregate (df2 by f),
          unnest_nested_data_frame (df3),
          matrix_from_data_frame (%%));

temperature_analysis_2 (df, grouping_field, f) :=
    block ([df1, df2, df3, df4, df5, h: make_array (hashed, 1)],
          df1: group (select ([grouping_field, "DATE_year", "TMIN", "TMAX"] from df) by "DATE_year"),
          for [[y], a] in df1@data
              /* coverage of TMAX is almost certainly the same as for TMIN,
               * but compute both and look at the smaller one, on general principle.
               */
              do if (c: min (simple_annual_coverage (a@data["TMIN"]), simple_annual_coverage (a@data["TMAX"]))) >= 0.9 then h[y]: a
                     else print ("temperature_analysis_2: omit year", y, "(simple annual coverage =", c, ")"),
          df2: nested_data_frame (df1@names, h),
          df3: unnest_nested_data_frame (df2),
          df4: group (select ([grouping_field, "TMIN", "TMAX"] from df3) by grouping_field),
          df5: aggregate (df4 by f),
          unnest_nested_data_frame (df5),
          matrix_from_data_frame (%%));

/* Assume there is exactly one value, be it missing or not, per day.
 * Assess coverage as the proportion of nonmissing values per nominal year.
 */

simple_annual_coverage (l) :=
    block ([n_not_missing: lsum (if x # false then 1 else 0, x, l)],
           n_not_missing / 365.2425);

clean (l) := sublist (l, lambda ([x], x # false));

clean_mean (l) := block ([n], l: clean (l), n: length (l), if n > 0 then float (lsum (x, x, l) / n));

defstruct (min_max (min, max));

clean_range (l) := block ([n], l: clean (l), min_max (lmin (l), lmax (l)));

map_over_df (f, df) :=
    block ([h: make_array (hashed, 1)],
            for [[k], df1] in df@data
                do (print ("map_over_df: process key", k, "..."),
                    h[k]: f (df1)),
            nested_data_frame (df@names, h));

foo (df) := matrix_from_data_frame (unnest_nested_data_frame (df));

fpprintprec: 6;

temperature_df_1: map_over_df (foo, map_over_df (lambda ([df], temperature_analysis (df, "DATE_year",  clean_mean)), df1b_by_STATION));
temperature_df_10: map_over_df (foo, map_over_df (lambda ([df], temperature_analysis (df, "DATE_decade", clean_mean)), df1b_by_STATION));
temperature_df_30: map_over_df (foo, map_over_df (lambda ([df], temperature_analysis (df, "DATE_30year", clean_mean)), df1b_by_STATION));
temperature_df_100: map_over_df (foo, map_over_df (lambda ([df], temperature_analysis (df, "DATE_century", clean_mean)), df1b_by_STATION));

/* now print out results for each station */

map_over_df (print, temperature_df_1);
map_over_df (print, temperature_df_10);
map_over_df (print, temperature_df_30);
map_over_df (print, temperature_df_100);
